<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Laptop" ignored="0" name="Test" tests="4" failures="1" timestamp="2022-04-29T22:58:24 IST" time="0.079" errors="0">
  <testcase name="demopassword" time="0.012" classname="com.testngfeatures.Retry_Analyzer">
    <skipped/>
  </testcase> <!-- demopassword -->
  <testcase name="demopassword" time="0.001" classname="com.testngfeatures.Retry_Analyzer">
    <skipped/>
  </testcase> <!-- demopassword -->
  <testcase name="demopassword" time="0.002" classname="com.testngfeatures.Retry_Analyzer">
    <failure type="java.lang.AssertionError" message="expected [678] but found [123]">
      <![CDATA[java.lang.AssertionError: expected [678] but found [123]
at com.testngfeatures.Retry_Analyzer.demopassword(Retry_Analyzer.java:21)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- demopassword -->
  <testcase name="demousername" time="0.001" classname="com.testngfeatures.Retry_Analyzer"/>
</testsuite> <!-- Test -->
